### ISSUE TITLE
[Bug]: how would i disable infinite scan range?

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#126] opened 2024-01-01 18:24 UTC
### What happened?

sdasda

### Current Commit Hash

wedqe124

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment] 2024-01-01 18:25
Duplicate of #107

**Closed by winstxnhdw** 2024-01-01 18:25 UTC
Labels: bug
