### ISSUE TITLE
[Bug]: Suggestion for scan, hoarding bug revive 

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#62] opened 2023-12-25 04:15 UTC
### What happened?

I have a suggestion, It would help greatly. I was wondering fi you could make it so you can always scan and you can scan players too. For example, if dead, you could scan players. Or with esp mod you can always see players and monsters, even when dead. 

Also here's a pic of an example (but also player ID number with it would be nice and box. Also red color too.)
![Lethal Company Screenshot 2023 12 24 - 22 27 20 42](https://github.com/winstxnhdw/lc-hax/assets/143763241/71d0b1eb-552e-48de-9933-0074c773ee3f)

Also hoarding bug revive doesn't work for other players.

### Current Commit Hash

caczc

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment] 2023-12-25 08:45
Duplicate of #35 and #10

I can’t replicate your issue with the hoarding bug.

**Closed by winstxnhdw** 2023-12-25 08:45 UTC
Labels: bug
