### ISSUE TITLE
[Bug]: Unusual error when launching

### ISSUE THREAD

**Issue by joep26020** [winstxnhdw/lc-hax#494] opened 2024-03-30 23:14 UTC
### What happened?

My friend has this error when trying to launch regular vanilla mode. Antivirus was disabled and the requirements worked no problem. Everything was installed correctly (git, Microsoft sdk)
![image](https://github.com/winstxnhdw/lc-hax/assets/143763241/c6428cce-57dd-4a3b-9240-f7ec5bfbd6bc)

### Current Commit Hash

xcgfxb

### Injector

- [ ] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I did not have any other mods other than `lc-hax` installed when the issue occurred
- [X] I have confirmed that my anti-virus is not blocking any of the relevant programs
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment] 2024-03-30 23:17
Dupe of #459

**Closed by winstxnhdw** 2024-03-30 23:17 UTC
Labels: bug

**Comment by joep26020** [comment] 2024-03-31 02:30
> Dupe of #459

Thank you!

**Comment by joep26020** [comment] 2024-04-01 00:35
> Dupe of #459

hello?

**Comment by winstxnhdw** [comment] 2024-04-01 01:20
Well, they could try running the injector as admin instead.

**Comment by joep26020** [comment] 2024-04-01 01:27
> Well, they could try running the injector as admin instead.

it works now. thanks
