### ISSUE TITLE
Shovel command flat out doesn't work

### ISSUE THREAD

**Issue by Quesoteric** [winstxnhdw/lc-hax#2] opened 2023-12-10 23:21 UTC
Trying to use the shovel command does nothing

**Comment by winstxnhdw** [comment] 2023-12-11 03:18
You may want to describe your issue better.

**Comment by Quesoteric** [comment] 2023-12-11 04:24
v45, would try to describe it more if I got an error message or something like that, but running the shovel command doesn't result in the "/shovel <force=1>" message. I am using a shovel

**Comment by winstxnhdw** [comment] 2023-12-11 04:27
You are saying that when you do `/shovel` with no arguments, no message appears?

**Comment by winstxnhdw** [comment] 2023-12-11 04:31
I do see a bug with how we were handling the argument indexing, but you should’ve still seen the help message when running the command without arguments. Anyways, I have pushed a fix. You can pull and try it again.

**Comment by Quesoteric** [comment] 2023-12-11 04:33
> You are saying that when you do `/shovel` with no arguments, no message appears?

With absolutely nothing, the message appears. With anything else it doesn't

**Comment by winstxnhdw** [comment] 2023-12-11 04:34
Okay, great. That’s the intended behaviour. The issue should be fixed with the latest commit then.

**Closed** 2023-12-11 04:34 UTC
Labels: bug
