### ISSUE TITLE
Enemy esp/notifier

### ISSUE THREAD

**Issue by AverageVirusTotalEnjoyer** [winstxnhdw/lc-hax#67] opened 2023-12-26 00:48 UTC
Self explanatory show a box of where the enemy is, what enemy, or just a notification of one spawning

**Comment by winstxnhdw** [comment] 2023-12-26 00:49
Duplicate of #10

**Closed by winstxnhdw** 2023-12-26 00:49 UTC

**Comment by AverageVirusTotalEnjoyer** [comment] 2023-12-26 00:50
Mb, merry christmas anyways
