### ISSUE TITLE
[Bug]: Possess enemy not working

### ISSUE THREAD

**Issue by jezbud** [winstxnhdw/lc-hax#103] opened 2023-12-29 14:11 UTC
### What happened?

Not really sure how M3/Trigger works.
Everything works fine apart from anything using M3.

I click my scroll wheel and the enemy despawns

### Current Commit Hash

.

### Injector

- [X] SharpMonoInjectorCore
- [ ] Others

### Acknowledgement

- [X] I have **recursively** cloned the repository as instructed in the [README](https://github.com/winstxnhdw/lc-hax/edit/main/README.md)
- [X] I have done my due diligence to check for similar issues

**Comment by winstxnhdw** [comment] 2023-12-29 14:16
Duplicate of #50

**Closed by winstxnhdw** 2023-12-29 14:16 UTC
Labels: duplicate
