### ISSUE TITLE
Would it be possible to revive any player and/or yourself?

### ISSUE THREAD

**Issue by MythicalTrashcan** [winstxnhdw/lc-hax#45] opened 2023-12-24 06:07 UTC
This could be client side and/or server side. If this is possible, it would be quite helpful. I understand that their is god mode, but it doesn't seem smart to enable that in huge public lobbies.

**Comment by winstxnhdw** [comment] 2023-12-24 08:47
Not possible. I've tried.

**Comment by winstxnhdw** [comment] 2023-12-24 10:36
Duplicate of #35

**Closed by winstxnhdw** 2023-12-24 10:36 UTC
Labels: duplicate
